### ISSUE TITLE
Update with QE_ALLOW_STEP_BACK seems to have broken the config tab

### ISSUE THREAD

**Issue by MichielLassche** [JvdBosch/vroomissues#33]
![image](https://github.com/JvdBosch/vroomissues/assets/109032712/9e4a9543-2492-46d8-9fee-b6ffc9ca3d61)
 
--- log from Vizard ---
[16078.6083][WARNING] XMLProxyItem --> Received request for unknown attribute [QE_NO_UNDO]...
Traceback (most recent call last):
  File "C:\Working folder\vroomauthoring\nodescenemodel.py", line 198, in _selectionChanged
    self._mainwindow.display_nodeproperties(self.nodes_selected()[0])
  File "C:\Working folder\vroomauthoring\trainingdesigner.py", line 3492, in display_nodeproperties
    widget = node.xmlproxyitem.get_widget(parent=self.nodeFrame)
  File "C:\Working folder\vroomauthoring\bubblemodel.py", line 1133, in get_widget
    return self.widget.get_widget(self, *args, **kw)
  File "C:\Working folder\vroomauthoring\bubblewidgets.py", line 5053, in get_widget
    scroll.setWidget(tab.get_widget(xmlproxyitem, parent=widget))
  File "C:\Working folder\vroomauthoring\bubblewidgets.py", line 5018, in get_widget
    new_widget = wdgt.get_widget(xmlproxyitem, parent=widget)
  File "C:\Working folder\vroomauthoring\bubblewidgets.py", line 4988, in get_widget
    if attr.expertlevel & bubblewindow.mainwindow.expertlevel:
AttributeError: 'NoneType' object has no attribute 'expertlevel'

**Comment by MichielLassche** [comment]
Fixed the issue, QE_NO_UNDO wasn't referenced with the correct attribute
